# Generated by Django 4.1.2 on 2022-10-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0004_ruoli_alter_collaboratori_ruolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratori',
            name='ruolo',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ruoli',
        ),
    ]
