# Generated by Django 4.1.2 on 2022-10-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0006_ruoli_alter_collaboratori_ruolo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collaboratori',
            new_name='collaboratore',
        ),
        migrations.RenameModel(
            old_name='ruoli',
            new_name='ruolo',
        ),
    ]
