# Generated by Django 4.1.2 on 2022-10-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0007_rename_collaboratori_collaboratore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratore',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
