# Generated by Django 4.1.2 on 2022-10-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0008_collaboratore_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboratore',
            name='slug',
        ),
    ]
