# Generated by Django 4.1.2 on 2022-11-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0009_remove_collaboratore_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratore',
            name='ruolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azienda.ruolo', to_field='nome'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
