# Generated by Django 4.1.2 on 2022-11-14 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0010_alter_collaboratore_ruolo_alter_ruolo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratore',
            name='ruolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azienda.ruolo'),
        ),
    ]
