# Generated by Django 4.1.2 on 2022-10-10 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0007_rename_collaboratori_collaboratore_and_more'),
        ('intervista', '0002_remove_cliente_id_cliente_codicefiscale_intervista'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervista',
            name='collaboratore',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='azienda.collaboratore'),
            preserve_default=False,
        ),
    ]
