# Generated by Django 4.1.2 on 2022-10-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervista', '0003_intervista_collaboratore'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervista',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
