# Generated by Django 4.1.2 on 2022-10-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervista', '0004_intervista_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervista',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
